### ISSUE TITLE
Subnetwork should be specified for custom subnetmode network

### ISSUE THREAD

**Issue by 3thanZ** [terraform-google-modules/terraform-google-gsuite-export#4]
I encounter the following error when attempting to create the G Suite Export VM as part of a Shared VPC:
```
1 error(s) occurred:

* module.core.module.log_export.module.gsuite_export.google_compute_instance.gsuite_exporter_vm: 1 error(s) occurred:

* google_compute_instance.gsuite_exporter_vm: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0]': '{  "network": "projects/gcp-demo015-vpchost-sharedsvc/global/networks/gcp-demo015-vpchost-sharedsvc-...'. Subnetwork should be specified for custom subnetmode network, invalid
```

My Terraform script is as below:
```
module "gsuite_export" {
  source          = "terraform-google-modules/gsuite-export/google"
  version         = "~> 0.1.0"
  admin_user      = "${var.gsuite_export_admin_user}"
  api             = "reports_v1"
  applications    = "${var.gsuite_export_applications}"
  service_account = "${google_service_account.gsuite_export_service_account.email}"
  frequency       = "${var.gsuite_export_frequency}"
  project_id      = "${module.log_export_project.project_id}"
  machine_zone    = "${var.gsuite_export_machine_zone}"
  machine_name    = "${module.log_export_project.project_id}-gsuiteexporter-vm"
  machine_type    = "${var.gsuite_export_machine_type}"
  machine_image   = "${var.gsuite_machine_image}"
  machine_network = "${var.gsuite_export_machine_network}"
  export_filter   = "${var.gsuite_export_filter}"
}
```

Am I correct believe that a new variable called `machine_subnet` is required for this case to be passed into the google_compute_instance's subnetwork argument of the network_interface block?

**Comment by aaron-lane** [comment]
Hi @3thanZ. Thank you for your interest in the project!

Your assessment appears to be correct. We will add this request to our backlog and get to it as soon as possible.

**Comment by GoldM00n** [comment]
any way to make the export at the organisation level? for token activity data...

**Comment by 3thanZ** [comment]
@GoldM00n gsuite exporter does in fact export Google Admin logs at the organisation level. More information here https://github.com/GoogleCloudPlatform/professional-services/blob/master/tools/gsuite-exporter/README.md

**Comment by ocervell** [comment]
@3thanZ Noted, feel free to make a PR if you can, or else I will address it when I have some bandwith. Ideally, we should make the VM have a private IP and support any network (Shared VPC, Standalone).

@GoldM00n the logs are exported form GSuite Admin API for the whole organization, and end up in one project, and the log export is made on that project.

**Comment by 65156** [comment]
also encountering this issue, what is the solution? create a separate vpc for the exporter vm's? is there no way to deploy to a shared vpc?

can fix this by swapping the network to a subnetwork and adding 2 new variables for region and subnetwork.

**Comment by 65156** [comment]
im trying to fix this, but I dont have permissions to perform a pull-request @aaron-lane @ocervell ?

**Comment by morgante** [comment]
@frasercarter Anyone can create a pull request, you just need to fork first - https://gist.github.com/Chaser324/ce0505fbed06b947d962
