### ISSUE TITLE
Support for Terraform 0.12

### ISSUE THREAD

**Issue by WandLZhang** [terraform-google-modules/terraform-google-gsuite-export#5]
There are conflicting dependencies between your terraform-google-gsuite-export and the other [terraform-google-log-export](https://github.com/terraform-google-modules/terraform-google-log-export) project. 

terraform-google-log-export requires Terraform 0.12+, but when I do `terraform apply` I get an error related to the gsuite-export module:
```
Error: Unsupported block type

  on .terraform/modules/gsuite-export/main.tf line 37, in data "template_file" "gsuite_exporter":
  37:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.
```
terraform-google-log-export v2.0 and above seem to require Terraform 0.12. Here are the tf files I used: https://github.com/WandLZhang/drive-terraform

**Comment by aaron-lane** [comment]
Fixed by #15.
