### ISSUE TITLE
Segregating duties with two service accounts

### ISSUE THREAD

**Issue by WandLZhang** [terraform-google-modules/terraform-google-gsuite-export#6]
The README instructs setting up two service accounts, but the `main.tf` examples all show using just one service account that does the job of the Terraform setup and gsuite-export VM. It'd be clearer if the documentation showed just one of those options (I personally would like two service accounts in order to segregate duties).

**Comment by ocervell** [comment]
@WandLZhang One of those is used for running the Terraform, the other one is the service account running the VM. What's not clear ?

**Comment by WandLZhang** [comment]
The main.tf examples don't call out two service accounts, e.g. in pubsub directory:

```tf
provider "google" {
  credentials = "${file(var.credentials_path)}"
}

module "gsuite-export" {
  source          = "../../"
  **service_account = "${var.service_account}"**
  api             = "${var.api}"
  applications    = "${var.applications}"
  admin_user      = "${var.admin_user}"
  project_id      = "${var.project_id}"
  machine_name    = "${var.machine_name}"
}

module "gsuite-log-export" {
  source  = "github.com/terraform-google-modules/terraform-google-log-export"
  name    = "${var.export_name}"
  project = "${var.project_id}"
  filter  = "${module.gsuite-export.filter}"
  pubsub  = "${var.pubsub}"
}
```

so it's not clear there's that segregation

**Comment by ocervell** [comment]
Yes; in the example you copied, the Terraform service account is identified by the `var.credentials_path`, the VM service account is identified by the `var.service_account`. It's pretty standard but feel free to make a PR to clarify or let me know how it could be clearer.

**Comment by WandLZhang** [comment]
got it, thanks for helping this terraform novice. I might PR a version that changes `service_account` to `vm_service_account`
